[workspace]
members = ["savvy", "savvy-macro", "savvy-bindgen"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Hiroaki Yutani"]
license = "MIT"
homepage = "https://github.com/yutannihilation/savvy/"
documentation = "https://github.com/yutannihilation/savvy/"
