[package]
name = "unextendr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.69"
libR-sys = { git = "https://github.com/extendr/libR-sys" }
thiserror = "1.0.38"
