[package]
name = "savvy"
version = "0.1.0"
edition = "2021"

[dependencies]
libR-sys = { git = "https://github.com/extendr/libR-sys" }
once_cell = "1"

savvy-macro = { path = "../savvy-macro" }

[build-dependencies]
cc = "1"
