[package]
name = "savvy-cli"
description = "A CLI for savvy framework"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
savvy-bindgen = { version = "0", path = "../savvy-bindgen" }
walkdir = "2"

[package.metadata.dist]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu", # added
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
