[package]
name = "savvy-cli"
description = "A CLI for savvy framework"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
savvy-bindgen = { version = "0", path = "../savvy-bindgen" }
walkdir = "2"

[package.metadata.release]
release = true

[package.metadata.dist]
dist = true
