[book]
authors = ["Hiroaki Yutani"]
language = "en"
multilingual = false
src = "src"
title = "Savvy - A simple R extension interface using Rust"

[output.html]
site-url = "/savvy/guide/"
git-repository-url = "https://github.com/yutannihilation/savvy"
